webfactory_exceptions:
    path:      /_error/{code}/{_format}
    defaults:  { _controller: WebfactoryExceptionsBundle:Test:testErrorPage, _format: "html" }
    requirements:
        code:  \d+
